server.port=8081
logging.level.de.ereznik.aifootballpredictor=DEBUG
# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
# Football Data
football-data.token=${FOOTBALL_DATA_TOKEN}
# AI Models
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.anthropic.api-key=${SPRING_AI_ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-haiku-4-5-20251001
spring.ai.openai.chat.options.model=gpt-5.4-nano