server.port=8081
logging.level.de.ereznik.aifootballpredictor=DEBUG
# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
# Football Data
football-data.token=${FOOTBALL_DATA_TOKEN}
# Brave
brave.api_key=${BRAVE_API_KEY}
# AI Models
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini
spring.ai.anthropic.api-key=${SPRING_AI_ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-6
spring.ai.mistralai.api-key=${SPRING_AI_MISTRAL_API_KEY}
spring.ai.mistralai.chat.options.model=mistral-medium-latest