server.port=8081
logging.level.de.ereznik.aifootballpredictor=DEBUG
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
football-data.token=${FOOTBALL_DATA_TOKEN}
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.anthropic.api-key=${SPRING_AI_ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-haiku-4-5-20251001
spring.ai.openai.chat.options.model=gpt-5.4-nano
# DB
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true